@Gateway_HostAddress = http://localhost:5000

GET {{Gateway_HostAddress}}/health
Accept: application/json

###

GET {{Gateway_HostAddress}}/api/orders
Accept: application/json

###

GET {{Gateway_HostAddress}}/api/payments?orderId=00000000-0000-0000-0000-000000000000
Accept: application/json

###

GET {{Gateway_HostAddress}}/api/inventory/items
Accept: application/json

###
